on: push
jobs:
  build:
    name: WebGLビルドを実行
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{secrets.UNITY_LICENSE}}
        with:
          targetPlatform: WebGL
      - uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: build
          target-folder: My Project
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
